# Generated by Django 5.1.7 on 2025-03-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRestoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Backup & Restore', max_length=255)),
            ],
            options={
                'verbose_name': 'Backup & Restore',
                'verbose_name_plural': 'Backup & Restore',
            },
        ),
    ]
