# Generated by Django 5.1.7 on 2025-03-23 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence_images/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('banner', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Español')], max_length=2)),
                ('scope', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCoverTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tipo_analisis', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen_proveedor', models.ImageField(upload_to='imagenes/')),
                ('header_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('customer_header_image', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fqdn', models.CharField(blank=True, max_length=255, null=True)),
                ('urlAddress', models.URLField(blank=True, max_length=1024, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('owned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('hosts_affected', models.TextField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence', models.TextField()),
                ('description_es', models.TextField(blank=True, null=True)),
                ('solution_es', models.TextField(blank=True, null=True)),
                ('risk_factor', models.CharField(blank=True, max_length=50, null=True)),
                ('cvss_temporal_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('see_also', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='PortVulnerabilityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.port')),
            ],
        ),
    ]
