# Generated by Django 3.1.14 on 2024-02-12 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Español')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('hosts_affected', models.TextField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence', models.TextField()),
                ('description_es', models.TextField(blank=True, null=True)),
                ('solution_es', models.TextField(blank=True, null=True)),
                ('risk_factor', models.CharField(blank=True, max_length=50, null=True)),
                ('cvss_temporal_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('see_also', models.TextField(blank=True, null=True)),
                ('port_nessus', models.IntegerField(blank=True, null=True)),
                ('evidence_images', models.ManyToManyField(blank=True, to='ProjectManager.EvidenceImage')),
                ('port', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.port')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project')),
            ],
        ),
        migrations.CreateModel(
            name='PortVulnerabilityProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.port')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.vulnerability')),
            ],
            options={
                'unique_together': {('port', 'vulnerability', 'project')},
            },
        ),
        migrations.AddField(
            model_name='port',
            name='vulnerabilities',
            field=models.ManyToManyField(related_name='ports', through='ProjectManager.PortVulnerabilityProject', to='ProjectManager.Vulnerability'),
        ),
    ]
