# Generated by Django 5.1.7 on 2025-03-23 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectManager', '0001_initial'),
        ('attack_narrative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attack_narratives',
            field=models.ManyToManyField(blank=True, related_name='projects', to='attack_narrative.writeup'),
        ),
        migrations.AddField(
            model_name='portvulnerabilityproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project'),
        ),
        migrations.AddField(
            model_name='evidenceimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManager.reportcovertemplate'),
        ),
        migrations.AddField(
            model_name='project',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManager.reporttemplate'),
        ),
        migrations.AddField(
            model_name='target',
            name='jumped_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jump_targets', to='ProjectManager.target'),
        ),
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project'),
        ),
        migrations.AddField(
            model_name='port',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ProjectManager.target'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='evidence_images',
            field=models.ManyToManyField(blank=True, to='ProjectManager.evidenceimage'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='port',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_vulnerabilities', to='ProjectManager.port'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='target_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.target'),
        ),
        migrations.AddField(
            model_name='portvulnerabilityproject',
            name='vulnerability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.vulnerability'),
        ),
        migrations.AddField(
            model_name='port',
            name='vulnerabilities',
            field=models.ManyToManyField(related_name='associated_ports', through='ProjectManager.PortVulnerabilityProject', to='ProjectManager.vulnerability'),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('ip_address', 'fqdn', 'urlAddress')},
        ),
        migrations.AlterUniqueTogether(
            name='portvulnerabilityproject',
            unique_together={('port', 'vulnerability', 'project')},
        ),
    ]
