# Generated by Django 3.1.14 on 2024-02-12 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='vulnerabilities',
            field=models.ManyToManyField(related_name='associated_ports', through='ProjectManager.PortVulnerabilityProject', to='ProjectManager.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='port',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_vulnerabilities', to='ProjectManager.port'),
        ),
    ]
