# Generated by Django 5.1.7 on 2025-04-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attack_narratives',
        ),
    ]
