# Generated by Django 5.0.2 on 2024-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_alter_vulnerability_options_alter_evidenceimage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='vulnerabilities',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='port',
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='port',
            field=models.ManyToManyField(related_name='associated_vulnerabilities', through='ProjectManager.PortVulnerabilityProject', to='ProjectManager.port'),
        ),
    ]
