# Generated by Django 5.1.7 on 2025-04-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_remove_project_attack_narratives'),
        ('attack_narrative', '0003_writeupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attack_narratives',
            field=models.ManyToManyField(blank=True, related_name='projects', to='attack_narrative.writeup'),
        ),
    ]
