# Generated by Django 5.1.7 on 2025-04-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_project_attack_narratives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcovertemplate',
            old_name='nombre_cliente',
            new_name='analisys_type',
        ),
        migrations.RenameField(
            model_name='reportcovertemplate',
            old_name='imagen_proveedor',
            new_name='customer_image',
        ),
        migrations.RenameField(
            model_name='reportcovertemplate',
            old_name='tipo_analisis',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='reportcovertemplate',
            old_name='fecha_fin',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reportcovertemplate',
            old_name='header_imagen',
            new_name='header_image',
        ),
        migrations.RenameField(
            model_name='reportcovertemplate',
            old_name='fecha_inicio',
            new_name='start_date',
        ),
    ]
