# Generated by Django 5.1.7 on 2025-04-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_rename_nombre_cliente_reportcovertemplate_analisys_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='x_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='y_position',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
