# Generated by Django 5.1.7 on 2026-02-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_target_x_position_target_y_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='background_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code (e.g. #FFFFFF)', max_length=7),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='main_color',
            field=models.CharField(default='#000000', help_text='Hex color code for main text (e.g. #000000)', max_length=7),
        ),
    ]
