# Generated by Django 5.0.2 on 2024-03-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_remove_vulnerability_port_nessus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManager.reporttemplate'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fqdn', models.CharField(blank=True, max_length=255, null=True)),
                ('urlAddress', models.URLField(blank=True, max_length=1024, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('owned', models.BooleanField(default=False)),
                ('jumped_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jump_targets', to='ProjectManager.target')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project')),
            ],
            options={
                'unique_together': {('ip_address', 'fqdn', 'urlAddress')},
            },
        ),
        migrations.AddField(
            model_name='port',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='ProjectManager.target'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='target_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.target'),
        ),
    ]
