# Generated by Django 4.2.13 on 2024-07-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_projectmanager_client_reporttemplate_port_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
