# Generated by Django 4.2.13 on 2024-08-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0008_project_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCoverTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tipo_analisis', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen_proveedor', models.ImageField(upload_to='imagenes/')),
                ('header_imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectManager_client',
        ),
        migrations.AddField(
            model_name='project',
            name='cover_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjectManager.reportcovertemplate'),
        ),
    ]
