# Generated by Django 4.2.13 on 2024-08-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_reportcovertemplate_delete_projectmanager_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcovertemplate',
            name='customer_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
