# Generated by Django 5.1.7 on 2025-03-23 03:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_markdown', models.TextField(blank=True, null=True)),
                ('content_html', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_narratives_attack_narrative', to='ProjectManager.project')),
            ],
        ),
    ]
