# Generated by Django 5.1.7 on 2025-03-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_narrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='writeup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='writeups', to='attack_narrative.tag'),
        ),
    ]
