# Generated by Django 5.1.7 on 2025-03-31 19:06

import attack_narrative.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_narrative', '0002_tag_writeup_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=attack_narrative.models.writeup_image_path)),
                ('writeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attack_narrative.writeup')),
            ],
        ),
    ]
